In [6]:
import numpy as np
from scipy.io import loadmat

In [7]:
# load x1, x2, x3, R, C, K, img1, img2, img3 from a Matlab file

matfile = loadmat('./data.mat')
data = matfile['data']
x1 = data[0,0][0]
x2 = data[0,0][1]
x3 = data[0,0][2]
R = data[0,0][3]
C = data[0,0][4]
K = data[0,0][5]
img1 = data[0,0][6]
img2 = data[0,0][7]
img3 = data[0,0][8]


In [8]:
print (x1.shape)
print (x2.shape)
print (x3.shape)
print (R.shape)
print (C.shape)
print (K.shape)
print (img1.shape)
print (img2.shape)
print (img3.shape)

(429, 2)
(429, 2)
(429, 2)
(3, 3)
(3, 1)
(3, 3)
(960, 1280, 3)
(960, 1280, 3)
(960, 1280, 3)


In [9]:
print (R)
print (C)
print (K)

[[ 9.82380562e-01  1.34247835e-02  1.86408710e-01]
 [-1.30676840e-02  9.99909670e-01 -3.14433861e-03]
 [-1.86434083e-01  6.53007021e-04  9.82467254e-01]]
[[-0.92110865]
 [ 0.12895095]
 [ 0.36732888]]
[[568.99614085   0.         643.21055941]
 [  0.         568.9883624  477.98280104]
 [  0.           0.           1.        ]]


In [5]:
print (img1)
print (img2)
print (img3)


[[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 26 187 243]
  [ 26 187 243]
  [ 26 187 243]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 26 187 243]
  [ 27 188 244]
  [ 27 188 244]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [ 27 188 244]
  [ 27 188 244]
  [ 27 188 244]]

 ...

 [[ 88  81  98]
  [ 91  84 100]
  [ 95  87 102]
  ...
  [ 50  52  76]
  [ 50  52  76]
  [ 49  51  75]]

 [[ 88  81  98]
  [ 88  80  97]
  [ 88  80  94]
  ...
  [ 49  51  75]
  [ 49  51  75]
  [ 49  51  75]]

 [[ 77  70  87]
  [ 76  68  84]
  [ 75  66  79]
  ...
  [ 48  50  74]
  [ 48  50  74]
  [ 48  50  74]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 47 162 226]
  [ 47 162 226]
  [ 47 162 226]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 47 162 226]
  [ 47 162 226]
  [ 47 162 226]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 47 162 226]
  [ 47 162 226]
  [ 47 162 226]]

 ...

 [[ 33  32  49]
  [ 34  33  50]
  [ 34  33  50]
  ..

In [10]:
# compute F from x1, x2
# rank2 F
# normalize F

A = np.zeros((8,9))
for i in range(8):
    rowA = np.array([[x1[i,0]*x2[i,0], x1[i,0]*x2[i,1], x1[i,0]],
    [x1[i,1]*x2[i,0], x1[i,1]*x2[i,1], x1[i,1]],[x2[i,0], x2[i,1], 1]])
#     print(rowA)
    A[i,:] = np.reshape(rowA, (9,))

print(A, A.shape,"A")

(8, 9)
[[6.57312897e+05 4.10672572e+05 7.17520000e+02 5.27786932e+05
  3.29748006e+05 5.76130000e+02 9.16090000e+02 5.72350000e+02
  1.00000000e+00]
 [7.25281839e+05 1.41541662e+05 7.62740000e+02 2.18390906e+05
  4.26198619e+04 2.29670000e+02 9.50890000e+02 1.85570000e+02
  1.00000000e+00]
 [1.49617678e+05 1.01165584e+05 3.21130000e+02 1.41869595e+05
  9.59266350e+04 3.04500000e+02 4.65910000e+02 3.15030000e+02
  1.00000000e+00]
 [9.84702956e+05 5.93476499e+05 8.86090000e+02 7.30806530e+05
  4.40454147e+05 6.57620000e+02 1.11129000e+03 6.69770000e+02
  1.00000000e+00]
 [3.10747581e+05 2.87319343e+05 4.88190000e+02 3.76322901e+05
  3.47950733e+05 5.91210000e+02 6.36530000e+02 5.88540000e+02
  1.00000000e+00]
 [9.43279405e+04 1.31878775e+05 2.36050000e+02 2.26974484e+05
  3.17330333e+05 5.67990000e+02 3.99610000e+02 5.58690000e+02
  1.00000000e+00]
 [5.18036316e+04 8.49206796e+04 1.56360000e+02 1.82677708e+05
  2.99459992e+05 5.51380000e+02 3.31310000e+02 5.43110000e+02
  1.00000000e+00]

In [12]:
U,S,V = np.linalg.svd(A, full_matrices=True)
print(V, V.shape, "V")

[[-6.95920811e-01 -3.90939471e-01 -7.31987859e-04 -5.07623455e-01
  -3.24309895e-01 -5.74184045e-04 -9.41453016e-04 -5.68200251e-04
  -1.07829836e-06]
 [ 6.32843732e-01 -1.69261889e-01  3.18204371e-04 -2.92046790e-01
  -6.96825264e-01 -1.05742646e-03  1.65444693e-04 -1.09593066e-03
  -1.17909837e-06]
 [ 3.23070925e-01 -6.96497621e-01  1.25417895e-03 -2.75945162e-01
   5.78236298e-01  1.95219239e-03  2.24467228e-03  1.69409061e-03
   6.27058860e-06]
 [ 1.04054599e-01  5.77318367e-01 -5.55038614e-03 -7.62069925e-01
   2.73675509e-01 -7.04284983e-03 -9.94307209e-03 -6.92936001e-03
  -2.70129685e-05]
 [-3.46268041e-04  1.01281414e-02  5.50040646e-01 -1.09354689e-02
   1.24769928e-03  3.17690339e-01  7.04533718e-01  3.16122954e-01
   1.67772278e-03]
 [-7.93187323e-04 -2.82657318e-03  6.25187994e-01  3.23021752e-03
   5.39061017e-04 -3.73013066e-01 -1.22433898e-02 -6.85434476e-01
  -3.39977281e-03]
 [ 3.23295686e-04  5.63273003e-04  4.48965039e-01 -7.29973466e-04
  -5.43698788e-04  5.9192833

In [14]:
Varray = V[:,-1]
print(Varray, Varray.shape)

[-1.07829836e-06 -1.17909837e-06  6.27058860e-06 -2.70129685e-05
  1.67772278e-03 -3.39977281e-03 -4.83155024e-03 -1.51255632e-02
  9.99866741e-01] (9,)


In [16]:
F = V[:,-1].reshape((3,3))
print(F)

[[-1.07829836e-06 -1.17909837e-06  6.27058860e-06]
 [-2.70129685e-05  1.67772278e-03 -3.39977281e-03]
 [-4.83155024e-03 -1.51255632e-02  9.99866741e-01]]


In [17]:
U_hat,S_hat,V_hat = np.linalg.svd(F, full_matrices=True)
# print(S_hat.shape,S_hat)
S_hat[-1] = 0 
D = np.diag(S_hat)
F_rank2 = np.dot(U_hat, np.dot(np.diag(S_hat), V_hat.T))
F = F_rank2
print(F, F.shape, "F")

[[-1.44304843e-08 -1.22364001e-06 -6.26233152e-06]
 [-8.06781186e-06  1.71760621e-03  3.37989680e-03]
 [-4.83148537e-03 -2.67716344e-02 -9.99622710e-01]] (3, 3) F


In [19]:
F_norm = np.linalg.norm(F)
print(F_norm)
F_normalized = F / np.linalg.norm(F)
F = F_normalized
print(F_normalized, F_normalized.shape, "F_normalized")

1.0
[[-1.44304843e-08 -1.22364001e-06 -6.26233152e-06]
 [-8.06781186e-06  1.71760621e-03  3.37989680e-03]
 [-4.83148537e-03 -2.67716344e-02 -9.99622710e-01]] (3, 3) F_normalized


In [7]:
# compute E from F, K
# normalize E

print(K)
print(K.T)

E_noisy = K.T.dot(F.dot(K))
print(E_noisy)

U,singular_values_noisy,V = np.linalg.svd(E_noisy, full_matrices=True)
print(singular_values_noisy.shape,singular_values_noisy)

singular_values_noisy[0] = singular_values_noisy[1] = 1 
singular_values_noisy[-1] = 0 

singular_values_corrected = np.diag(singular_values_noisy)
print(singular_values_corrected.shape,singular_values_corrected)

E_corrected = U.dot(singular_values_corrected.dot(V.T))
E = E_corrected
print(E_corrected)

E_norm = np.linalg.norm(E)
print(E_norm)
E_normalized = E / np.linalg.norm(E)
E = E_normalized
print(E_normalized)


[[568.99614085   0.         643.21055941]
 [  0.         568.9883624  477.98280104]
 [  0.           0.           1.        ]]
[[568.99614085   0.           0.        ]
 [  0.         568.9883624    0.        ]
 [643.21055941 477.98280104   1.        ]]
[[-4.67196466e-03 -3.96156123e-01 -3.41638398e-01]
 [-2.61197170e+00  5.56071158e+02  4.66102080e+02]
 [-4.94858363e+00  4.51451035e+02  3.74262569e+02]]
(3,) [9.32934829e+02 3.31338443e+00 5.61998126e-15]
(3, 3) [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[-0.00262508  0.00125301  0.00188991]
 [ 0.47830125  0.21937124 -0.85035138]
 [-0.60056775  0.78818051 -0.1344787 ]]
1.414213562373095
[[-0.00185621  0.00088601  0.00133637]
 [ 0.33821006  0.15511889 -0.60128923]
 [-0.42466553  0.55732778 -0.0950908 ]]


In [8]:
# linear triangulation
# matrix cat

C1 = np.ones((3,1))
print(C1, C1.shape)

C1_minus = np.dot(-1, C1)
print(C1_minus, C1_minus.shape)

I = np.eye(3)
print(I, I.shape)

T = np.hstack((np.eye(3), C1_minus))
print(T, T.shape)

T = np.concatenate((np.eye(3), C1_minus), axis=1)
print(T, T.shape)

[[1.]
 [1.]
 [1.]] (3, 1)
[[-1.]
 [-1.]
 [-1.]] (3, 1)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]] (3, 4)
[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]] (3, 4)


In [9]:
# linear triangulation
# compute P1

R1 = np.eye(3)
C1 = np.zeros((3,1))
print(R1)
print(C1)

C1_minus = np.dot(-1.0,C1)
print(C1_minus, C1_minus.shape)

I_C1 = np.hstack((np.eye(3),C1_minus))
print(I_C1, I_C1.shape)

K_R1 = np.dot(K,R1)
print(K_R1, K_R1.shape)

P1 = np.dot(K_R1, I_C1)
print(P1, P1.shape)

# P1=dot(dot(K,R1),cat(np.eye(3),dot(-1.0,C1)))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]] (3, 1)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)
[[568.99614085   0.         643.21055941]
 [  0.         568.9883624  477.98280104]
 [  0.           0.           1.        ]] (3, 3)
[[568.99614085   0.         643.21055941   0.        ]
 [  0.         568.9883624  477.98280104   0.        ]
 [  0.           0.           1.           0.        ]] (3, 4)


In [11]:
# linear triangulation
# compute P2

R2 = R
C2 = C
print(R2)
print(C2)

C2_minus = np.dot(-1.0,C2)
print(C2_minus, C2_minus.shape)

I_C2 = np.hstack((np.eye(3),C2_minus))
print(I_C2, I_C2.shape)

K_R2 = np.dot(K,R2)
print(K_R2, K_R2.shape)

P2 = np.dot(K_R2, I_C2)
print(P2, P2.shape)

[[ 9.82380562e-01  1.34247835e-02  1.86408710e-01]
 [-1.30676840e-02  9.99909670e-01 -3.14433861e-03]
 [-1.86434083e-01  6.53007021e-04  9.82467254e-01]]
[[-0.92110865]
 [ 0.12895095]
 [ 0.36732888]]
[[ 0.92110865]
 [-0.12895095]
 [-0.36732888]] (3, 1)
[[ 1.          0.          0.          0.92110865]
 [ 0.          1.          0.         -0.12895095]
 [ 0.          0.          1.         -0.36732888]] (3, 4)
[[ 4.39054377e+02  8.05867101e+00  7.37999149e+02]
 [-9.65476455e+01  5.69249092e+02  4.67813358e+02]
 [-1.86434083e-01  6.53007021e-04  9.82467254e-01]] (3, 3)
[[ 4.39054377e+02  8.05867101e+00  7.37999149e+02  1.32289206e+02]
 [-9.65476455e+01  5.69249092e+02  4.67813358e+02 -3.34177444e+02]
 [-1.86434083e-01  6.53007021e-04  9.82467254e-01 -5.32698853e-01]] (3, 4)


In [12]:
# linear triangulation
# compute X from x1, x2

# dim = (len(x1),3)
print(x1.shape)
print(len(x1))

X = np.zeros((len(x1),3))
print(X, X.shape)

# print(np.arange(1, len(x1)))
# np.arange(1, len(x1)).reshape(-1)

c = 1
for i in np.arange(1, len(x1)).reshape(-1):
    a = x1[i - 1,0]
    b = x1[i - 1,1]
    x1mat = np.array([0, -c, b, c, 0, -a, -b, a, 0]).reshape((3,3))
#     print(a, a.shape)
#     print(b, b.shape)
#     print(x1mat, x1mat.shape)
    
    a = x2[i - 1,0]
    b = x2[i - 1,1]
    x2mat = np.array([0, -c, b, c, 0, -a, -b, a, 0]).reshape((3,3))
#     print(a, a.shape)
#     print(b, b.shape)
#     print(x2mat, x2mat.shape)

    x1p1 = np.dot(x1mat,P1)
    print(x1p1, x1p1.shape)
    x2p2 = np.dot(x2mat,P2)
    print(x2p2, x2p2.shape)
    A = np.vstack((x1p1, x2p2))
    print(A, A.shape)
    
    U,S,V = np.linalg.svd(A, full_matrices=True)
    X[i - 1,:] = V[0:3,3] / V[3,3]
    print(X[i - 1,:])
    print(V, V.shape)
    print(V[0:3,3], V[0:3,3].shape)
    print(V[3,3])
    print(V[0:3,3] / V[3,3])

print(X, X.shape)

(429, 2)
429
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (429, 3)
[[ 0.00000000e+00 -5.68988362e+02  9.81471990e+01  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -7.43094406e+01  0.00000000e+00]
 [-3.27815747e+05  4.08260530e+05 -2.76106802e+04  0.00000000e+00]] (3, 4)
[[-1.01579021e+01 -5.68875343e+02  9.45017750e+01  2.92872557e+01]
 [ 6.09844777e+02  7.46045780e+00 -1.62029278e+02  6.20289299e+02]
 [-3.39739105e+05  5.16871020e+05  6.16532650e+03 -3.81852342e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02  9.81471990e+01  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -7.43094406e+01  0.00000000e+00]
 [-3.27815747e+05  4.08260530e+05 -2.76106802e+04  0.00000000e+00]
 [-1.01579021e+01 -5.68875343e+02  9.45017750e+01  2.92872557e+01]
 [ 6.09844777e+02  7.46045780e+00 -1.62029278e+02  6.20289299e+02]
 [-3.39739105e+05  5.16871020e+05  6.16532650e+03 -3.81852342e+05]] (6, 4)
[-2.82621088 -7.07329259  0.98157488]
[[-0.53807268  0.75971596 -0.01208

[[ 3.77183705e+01 -5.69043036e+02 -1.57795816e+02  1.66084321e+02]
 [ 5.90709183e+02  7.52748245e+00 -6.11888394e+01  5.65613089e+02]
 [-2.17080291e+05  4.60512760e+05  1.47667145e+05 -3.13580501e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02 -1.41692801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -1.92944059e+00  0.00000000e+00]
 [-1.91347712e+05  3.67077152e+05  9.20605452e+04  0.00000000e+00]
 [ 3.77183705e+01 -5.69043036e+02 -1.57795816e+02  1.66084321e+02]
 [ 5.90709183e+02  7.52748245e+00 -6.11888394e+01  5.65613089e+02]
 [-2.17080291e+05  4.60512760e+05  1.47667145e+05 -3.13580501e+05]] (6, 4)
[ 3.64762377  9.28040737 -0.75412517]
[[-0.39512109  0.80900053  0.24013119 -0.36295245]
 [ 0.22821033 -0.30802635  0.01749418 -0.92343585]
 [ 0.88981346  0.43974194  0.09606392  0.07503832]
 [-0.00560103  0.23930093 -0.96581711 -0.09950381]] (4, 4)
[-0.36295245 -0.92343585  0.07503832] (3,)
-0.09950380529277704
[ 3.64762377  9.28040737 -0.75412517]
[[ 0.00000000e+00 -5.68988362

[[ 0.00000000e+00 -5.68988362e+02 -2.54062801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  1.60280559e+02  0.00000000e+00]
 [-1.27409616e+05  2.74781550e+05  8.68045256e+04  0.00000000e+00]] (3, 4)
[[ 5.64624532e+01 -5.69108689e+02 -2.56573074e+02  2.19641864e+02]
 [ 5.56384803e+02  7.64770757e+00  1.19693207e+02  4.67537903e+02]
 [-1.55162377e+05  3.56518529e+05  1.35736462e+05 -2.38754735e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02 -2.54062801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  1.60280559e+02  0.00000000e+00]
 [-1.27409616e+05  2.74781550e+05  8.68045256e+04  0.00000000e+00]
 [ 5.64624532e+01 -5.69108689e+02 -2.56573074e+02  2.19641864e+02]
 [ 5.56384803e+02  7.64770757e+00  1.19693207e+02  4.67537903e+02]
 [-1.55162377e+05  3.56518529e+05  1.35736462e+05 -2.38754735e+05]] (6, 4)
[ 4.88497701 12.35650294 -0.97824225]
[[-0.35911554  0.80800845  0.29064487 -0.36562814]
 [ 0.19151171 -0.32828213 -0.01418461 -0.92485291]
 [ 0.87915497  0.29059179  0.370

[[ 3.98232113e+01 -5.69050408e+02 -1.68887871e+02  1.72098491e+02]
 [ 6.37069746e+02  7.36509919e+00 -3.05498972e+02  6.98079313e+02]
 [-2.36131870e+05  6.02158914e+05  2.72330303e+05 -3.95186861e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02 -1.39632801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -2.19129441e+02  0.00000000e+00]
 [-1.92519844e+05  4.90661424e+05  1.94553396e+05  0.00000000e+00]
 [ 3.98232113e+01 -5.69050408e+02 -1.68887871e+02  1.72098491e+02]
 [ 6.37069746e+02  7.36509919e+00 -3.05498972e+02  6.98079313e+02]
 [-2.36131870e+05  6.02158914e+05  2.72330303e+05 -3.95186861e+05]] (6, 4)
[ 4.47798274 12.12633892  0.24944827]
[[-0.31785825  0.81040452  0.35066649 -0.34531675]
 [ 0.12840481 -0.32645257 -0.0500123  -0.9351148 ]
 [ 0.871337    0.43305237 -0.22992923 -0.01923604]
 [-0.35107004  0.2216729  -0.90645702 -0.07711435]] (4, 4)
[-0.34531675 -0.9351148  -0.01923604] (3,)
-0.07711435481108357
[ 4.47798274 12.12633892  0.24944827]
[[ 0.00000000e+00 -5.68988362

 [-2.57424418e+05  6.16586098e+05  2.52891076e+05 -4.09519421e+05]] (6, 4)
[ -4.47270764 -11.92641653  -0.12115106]
[[-0.3418632   0.81210721  0.31792379 -0.35005128]
 [ 0.1517212  -0.32264095 -0.04042935 -0.93340718]
 [ 0.84474345  0.45910925 -0.27484049 -0.00948175]
 [ 0.38277766 -0.16001063  0.90650573  0.07826384]] (4, 4)
[-0.35005128 -0.93340718 -0.00948175] (3,)
0.0782638421845356
[ -4.47270764 -11.92641653  -0.12115106]
[[ 0.00000000e+00 -5.68988362e+02 -1.13612801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -1.32079441e+02  0.00000000e+00]
 [-2.07325124e+05  4.41130987e+05  1.36208654e+05  0.00000000e+00]] (3, 4)
[[ 3.39393516e+01 -5.69029799e+02 -1.37881205e+02  1.55286515e+02]
 [ 6.19925268e+02  7.42514972e+00 -2.15151283e+02  6.49092326e+02]
 [-2.41109905e+05  5.49556436e+05  2.06018933e+05 -3.68630951e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02 -1.13612801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -1.32079441e+02  0.00000000e+00]
 [-2.07325124e+05

 [ 0.71912524 -0.01040013 -0.69352715 -0.04208103]] (4, 4)
[-0.19233118 -0.76855173 -0.60874144] (3,)
-0.04208103155777099
[ 4.57049596 18.26361433 14.46593432]
[[ 0.00000000e+00 -5.68988362e+02  7.95719896e+00  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  5.27470559e+02  0.00000000e+00]
 [-2.76497985e+05  6.58547131e+04 -2.57240010e+05  0.00000000e+00]] (3, 4)
[[ 5.98542515e+00 -5.68931887e+02  9.42993539e+00  7.54136494e+01]
 [ 4.94861556e+02  7.86319988e+00  4.43907401e+02  2.91747281e+02]
 [-2.42175627e+05  1.66484443e+05 -2.18455216e+05 -1.64293481e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02  7.95719896e+00  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  5.27470559e+02  0.00000000e+00]
 [-2.76497985e+05  6.58547131e+04 -2.57240010e+05  0.00000000e+00]
 [ 5.98542515e+00 -5.68931887e+02  9.42993539e+00  7.54136494e+01]
 [ 4.94861556e+02  7.86319988e+00  4.43907401e+02  2.91747281e+02]
 [-2.42175627e+05  1.66484443e+05 -2.18455216e+05 -1.64293481e+05]] (6, 4)
[ -5.960361

[ -4.15427081 -14.9392898   -6.8912956 ]
[[-6.89178004e-01  4.09388210e-01 -5.45622966e-01 -2.44398344e-01]
 [ 3.19645960e-01  2.87993591e-01  2.06015750e-01 -8.78887742e-01]
 [-3.56413889e-01 -8.41786411e-01  1.81382583e-04 -4.05419221e-01]
 [-5.43901901e-01  2.02130212e-01  8.12313398e-01  5.88306240e-02]] (4, 4)
[-0.24439834 -0.87888774 -0.40541922] (3,)
0.05883062404704899
[ -4.15427081 -14.9392898   -6.8912956 ]
[[ 0.00000000e+00 -5.68988362e+02  1.34017199e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  4.61980559e+02  0.00000000e+00]
 [-3.48225638e+05  1.03117761e+05 -3.07020039e+05  0.00000000e+00]] (3, 4)
[[-1.48224829e+01 -5.68859005e+02  1.19083106e+02  1.59591304e+01]
 [ 5.05363388e+02  7.82641600e+00  3.88565020e+02  3.21754208e+02]
 [-2.96617015e+05  1.97650816e+05 -2.74471374e+05 -1.97882495e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02  1.34017199e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  4.61980559e+02  0.00000000e+00]
 [-3.48225638e+05  1.031177

[ 3.4087719   8.97535677 -0.31024609]
[[-0.33359841  0.80981855  0.32913284 -0.3529555 ]
 [ 0.16739832 -0.32858419 -0.01846547 -0.92933807]
 [ 0.92440619  0.37772395  0.04202219  0.03212391]
 [-0.07850538  0.30586101 -0.94316739 -0.1035433 ]] (4, 4)
[-0.3529555  -0.92933807  0.03212391] (3,)
-0.10354330174441664
[ 3.4087719   8.97535677 -0.31024609]
[[ 0.00000000e+00 -5.68988362e+02 -1.99932801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -3.21594406e+01  0.00000000e+00]
 [-1.58209377e+05  3.84277670e+05  1.43970548e+05  0.00000000e+00]] (3, 4)
[[ 5.01460665e+01 -5.69086565e+02 -2.23287083e+02  2.01594027e+02]
 [ 5.97707918e+02  7.50296856e+00 -9.80706602e+01  5.85610604e+02]
 [-1.91437325e+05  4.82419562e+05  2.14423882e+05 -3.17307124e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02 -1.99932801e+02  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00 -3.21594406e+01  0.00000000e+00]
 [-1.58209377e+05  3.84277670e+05  1.43970548e+05  0.00000000e+00]
 [ 5.01460665e+01 -5.69086565

[ 9.43089565 25.82826275  5.93497498]
[[-0.62226899  0.67530027 -0.21092215 -0.33505626]
 [ 0.36335349 -0.07610822  0.1420087  -0.91761392]
 [-0.63814724 -0.73049718 -0.12117007 -0.2108549 ]
 [ 0.27115245 -0.06746077 -0.95951195 -0.03552751]] (4, 4)
[-0.33505626 -0.91761392 -0.2108549 ] (3,)
-0.03552751229444785
[ 9.43089565 25.82826275  5.93497498]
[[ 0.00000000e+00 -5.68988362e+02  1.66771990e+01  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  3.60970559e+02  0.00000000e+00]
 [-2.81459631e+05  1.60591275e+05 -1.83264670e+05  0.00000000e+00]] (3, 4)
[[ 4.85563460e+00 -5.68927930e+02  1.53836869e+01  7.21854943e+01]
 [ 5.20222184e+02  7.77437134e+00  3.10262380e+02  3.64210306e+02]
 [-2.57969672e+05  2.43870562e+05 -1.59290840e+05 -2.10553311e+05]] (3, 4)
[[ 0.00000000e+00 -5.68988362e+02  1.66771990e+01  0.00000000e+00]
 [ 5.68996141e+02  0.00000000e+00  3.60970559e+02  0.00000000e+00]
 [-2.81459631e+05  1.60591275e+05 -1.83264670e+05  0.00000000e+00]
 [ 4.85563460e+00 -5.68927930

In [36]:
print(x3.shape)
print(len(x1))

print(X.shape)
print(len(X))

ones = np.ones((len(X),1))
print(ones.shape)

xc = np.hstack((x3, ones))
print(xc,xc.shape)

print(K,K.shape)

xc_t = xc.T
xc = np.linalg.solve(K,xc_t)
xc_t = xc.T
print(xc_t,xc_t.shape)

A = np.zeros((len(x3)*2,12))
# print(zeros,zeros.shape)

# print(np.arange(1, len(x3)))
# np.arange(1, len(x3)).reshape(-1)

j = 0
for i in np.arange(1, len(x3)).reshape(-1):
    xc0 = xc_t[i-1,0]
    xc1 = xc_t[i-1,1]
    
    X0 = X[i-1,0]
    X1 = X[i-1,1]
    X2 = X[i-1,2]
    
    # X2*xc0
    row = np.array([-X0, -X1, -X2, 0, 0, 0, xc0*X0, xc0*X1, xc0*X2, -1, 0, xc0])
    rowPlus = np.array([0, 0, 0, -X0, -X1, -X2, xc1*X0, xc1*X1, xc1*X2, 0, -1, xc1])
    
    A[j,:] = row
    A[j+1,:] = rowPlus
    j = j + 2
    



(429, 2)
429
(429, 3)
429
(429, 1)
[[9.78600e+02 5.39230e+02 1.00000e+00]
 [9.95650e+02 1.19090e+02 1.00000e+00]
 [4.37970e+02 2.92910e+02 1.00000e+00]
 ...
 [1.14954e+03 1.26940e+02 1.00000e+00]
 [1.07563e+03 4.49800e+01 1.00000e+00]
 [5.67050e+02 8.91500e+01 1.00000e+00]] (429, 3)
[[568.99614085   0.         643.21055941]
 [  0.         568.9883624  477.98280104]
 [  0.           0.           1.        ]] (3, 3)
[[ 0.58944062  0.10764227  1.        ]
 [ 0.61940568 -0.63075596  1.        ]
 [-0.36070642 -0.32526641  1.        ]
 ...
 [ 0.88986445 -0.61695954  1.        ]
 [ 0.75996902 -0.76100467  1.        ]
 [-0.13385075 -0.68337567  1.        ]] (429, 3)
